In [16]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [13]:
combined_data = pd.read_csv('Combined_dataset.csv')

print(combined_data.dtypes)

/var/folders/qn/t0tfgsq57qn5ld54tyxxhyjw0000gn/T/ipykernel_17014/1237917507.py:1: DtypeWarning: Columns (2,6,20,21) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_data = pd.read_csv('Combined_dataset.csv')

track_id             object
artists              object
album_name           object
track_name           object
popularity          float64
duration_ms           int64
explicit             object
danceability        float64
energy              float64
key                   int64
loudness            float64
mode                  int64
speechiness         float64
acousticness        float64
instrumentalness    float64
liveness            float64
valence             float64
tempo               float64
time_signature      float64
year                float64
genre                object
release_date         object
dtype: object

In [14]:
feature_cols = [
    'energy',
    'danceability',
    'key',
    'loudness',
    'mode',
    'speechiness',
    'acousticness',
    'instrumentalness',
    'liveness',
    'valence',
    'tempo',
    'time_signature'
]

features_table = combined_data[feature_cols]

,energy,danceability,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,0.4610,0.676,1,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4.0
1,0.1660,0.420,1,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4.0
2,0.3590,0.438,0,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4.0
3,0.0596,0.266,0,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3.0
4,0.4430,0.618,2,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4.0

In [25]:
scaler = StandardScaler()

scaled_values =  scaler.fit_transform(features_table)
features_table = pd.DataFrame(
    scaled_values,
    columns=feature_cols,
    index=features_table.index
)

features_table.head()

,energy,danceability,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,-0.384564,0.847400,-1.195766,0.564378,-1.372290,0.448245,-0.945123,-0.717243,0.764716,1.005964,-1.036677,0.272317
1,-1.402040,-0.511468,-1.195766,-1.042546,0.728709,-0.100353,1.430091,-0.717230,-0.581023,-0.652280,-1.379373,0.272317
2,-0.736369,-0.415923,-1.477778,0.106614,0.728709,-0.269785,-0.471572,-0.717246,-0.497242,-1.196392,-1.417395,0.272317
3,-1.769021,-1.328912,-1.477778,-1.238643,0.728709,-0.429347,1.379486,-0.717055,-0.418697,-1.111258,2.046635,-1.658343
4,-0.446647,0.539531,-0.913755,0.114733,0.728709,-0.295282,0.218247,-0.717246,-0.675801,-1.022424,0.015993,0.272317