In [1]:
import pandas as pd

In [2]:

spotify_data =  pd.read_csv('dataset.csv')

from itertools import islice

path = "userid-timestamp-artid-artname-traid-traname.tsv"

with open(path, encoding="utf-8", errors="replace") as file:
    row = next(islice(file, 2_120_259, 2_120_260), None)

print(repr(row))

FileNotFoundError: [Errno 2] No such file or directory: 'userid-timestamp-artid-artname-traid-traname.tsv'

In [ ]:
spotify_data.head(5)

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

In [ ]:
spotify_data.dtypes

Unnamed: 0            int64
track_id             object
artists              object
album_name           object
track_name           object
popularity            int64
duration_ms           int64
explicit               bool
danceability        float64
energy              float64
key                   int64
loudness            float64
mode                  int64
speechiness         float64
acousticness        float64
instrumentalness    float64
liveness            float64
valence             float64
tempo               float64
time_signature        int64
track_genre          object
dtype: object

In [ ]:
popular_tracks = spotify_data.loc[spotify_data["popularity"] > 70]

print("Tracks with popularity over 70:", len(popular_tracks))
display(popular_tracks.head())

Tracks with popularity over 70: 954

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.443,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic
2000,2000,5E30LdtzQTGqRvNd7l6kG5,The Neighbourhood,Wiped Out!,Daddy Issues,87,260173,False,0.588,0.521,...,-9.461,1,0.0329,0.0678,0.149000,0.1230,0.337,85.012,4,alt-rock
2001,2001,2Y0iGXY6m6immVb2ktbseM,MGMT,Little Dark Age,Little Dark Age,83,299960,False,0.705,0.712,...,-6.156,1,0.0385,0.0102,0.000855,0.1000,0.620,97.512,4,alt-rock
2002,2002,2K7xn816oNHJZ0aVqdQsha,The Neighbourhood,Hard To Imagine The Neighbourhood Ever Changing,Softcore,86,206280,False,0.575,0.568,...,-5.509,0,0.0300,0.0484,0.000417,0.2860,0.370,93.986,4,alt-rock
2003,2003,2QjOHCTQ1Jl3zawyYOpxh6,The Neighbourhood,I Love You.,Sweater Weather,93,240400,False,0.612,0.807,...,-2.810,1,0.0336,0.0495,0.017700,0.1010,0.398,124.053,4,alt-rock

In [ ]:
spotify_data = pd.read_csv(
    path,
    sep="\t",
    on_bad_lines="warn",
)

/var/folders/qn/t0tfgsq57qn5ld54tyxxhyjw0000gn/T/ipykernel_60584/380660365.py:1: ParserWarning: Skipping line 2120260: expected 6 fields, saw 8

  spotify_data = pd.read_csv(
/var/folders/qn/t0tfgsq57qn5ld54tyxxhyjw0000gn/T/ipykernel_60584/380660365.py:1: ParserWarning: Skipping line 2446318: expected 6 fields, saw 8

  spotify_data = pd.read_csv(
/var/folders/qn/t0tfgsq57qn5ld54tyxxhyjw0000gn/T/ipykernel_60584/380660365.py:1: ParserWarning: Skipping line 11141081: expected 6 fields, saw 8

  spotify_data = pd.read_csv(
/var/folders/qn/t0tfgsq57qn5ld54tyxxhyjw0000gn/T/ipykernel_60584/380660365.py:1: ParserWarning: Skipping line 11152099: expected 6 fields, saw 12
Skipping line 11152402: expected 6 fields, saw 8

  spotify_data = pd.read_csv(
/var/folders/qn/t0tfgsq57qn5ld54tyxxhyjw0000gn/T/ipykernel_60584/380660365.py:1: ParserWarning: Skipping line 11882087: expected 6 fields, saw 8

  spotify_data = pd.read_csv(
/var/folders/qn/t0tfgsq57qn5ld54tyxxhyjw0000gn/T/ipykernel_60584/380660365.py:1: ParserWarning: Skipping line 12902539: expected 6 fields, saw 8
Skipping line 12935044: expected 6 fields, saw 8

  spotify_data = pd.read_csv(
/var/folders/qn/t0tfgsq57qn5ld54tyxxhyjw0000gn/T/ipykernel_60584/380660365.py:1: ParserWarning: Skipping line 17589539: expected 6 fields, saw 8

  spotify_data = pd.read_csv(

In [ ]:
spotify_data.head(5)

,user_000001,2009-05-04T23:08:57Z,f1b1cf71-bd35-4e99-8624-24a6e15f133a,Deep Dish,Unnamed: 4,Fuck Me Im Famous (Pacha Ibiza)-09-28-2007
0,user_000001,2009-05-04T13:54:10Z,a7f7df4a-77d8-4f12-8acd-5c60c93f4de8,坂本龍一,NaN,Composition 0919 (Live_2009_4_15)
1,user_000001,2009-05-04T13:52:04Z,a7f7df4a-77d8-4f12-8acd-5c60c93f4de8,坂本龍一,NaN,Mc2 (Live_2009_4_15)
2,user_000001,2009-05-04T13:42:52Z,a7f7df4a-77d8-4f12-8acd-5c60c93f4de8,坂本龍一,NaN,Hibari (Live_2009_4_15)
3,user_000001,2009-05-04T13:42:11Z,a7f7df4a-77d8-4f12-8acd-5c60c93f4de8,坂本龍一,NaN,Mc1 (Live_2009_4_15)
4,user_000001,2009-05-04T13:38:31Z,a7f7df4a-77d8-4f12-8acd-5c60c93f4de8,坂本龍一,NaN,To Stanford (Live_2009_4_15)

In [ ]:
import pandas as pd

path = "userid-timestamp-artid-artname-traid-traname.tsv"

spotify_data = pd.read_csv(
    path,
    sep="\t",
    header=None,
    names=["userid", "date", "artist_id", "artist", "track_id", "song"],
    usecols=["userid", "date", "artist", "song"],
    on_bad_lines="skip",
)

spotify_data = spotify_data.sample(
    frac=0.25,
    random_state=42,
).reset_index(drop=True)

print(spotify_data.shape)
spotify_data.head()

(4774716, 4)

,userid,date,artist,song
0,user_000894,2008-10-18T15:43:10Z,Shakira,Sombra De Ti [Unplugged]
1,user_000610,2007-02-21T14:42:47Z,My Chemical Romance,Famous Last Words
2,user_000053,2006-11-26T02:56:17Z,The Roots,Game Theory
3,user_000689,2005-12-20T03:31:31Z,The Brian Jonestown Massacre,Here To Go
4,user_000543,2006-01-03T22:43:04Z,Eminem,My Dad'S Gone Crazy

In [ ]:
spotify_data.to_csv("spotify_data_sample.csv", index=False)

spotify_data